### ISSUE TITLE
Cannot download in package control

### ISSUE THREAD

**Issue by lrisora** [relikd/CUE-Sheet_sublime#2]
Very useful plug-in, but after reinstalling the system I found that I couldn't download it!
![2020-10-25 151434](https://user-images.githubusercontent.com/43085437/97101042-d78aae80-16d4-11eb-9d45-17fe5ce7b6f5.png)

**Comment by relikd** [comment]
Thank you, I would not have noticed otherwise.
I've created a PR to package control. Should be fixed once https://github.com/wbond/package_control_channel/pull/8085 is merged.

**Comment by relikd** [comment]
Finally merged today. Should be fixed now.
